import {
  Profile1,
  Profile10,
  Profile2,
  Profile3,
  Profile4,
  Profile5,
  Profile6,
  Profile7,
  Profile8,
} from "../assets/export";

export const subscriberList = [
  {
    image: Profile1,
    sub_date: "Jan 12, 2024",
    name: "Jane Smith",
    email: "jane.smith@gmail.com",
    number: "+1 000 000 0000",
    vin: "9090",
    plan: "DriveCar Plus",
    amount: "USD $100",
    duration: "Yearly",
    type: "Active",
  },
  {
    image: Profile2,
    sub_date: "Jan 12, 2024",
    name: "Jane Smith",
    email: "jane.smith@gmail.com",
    number: "+1 000 000 0000",
    vin: "9090",
    plan: "DriveCar Plus",
    amount: "USD $100",
    duration: "Yearly",
    type: "Active",
  },
  {
    image: Profile3,
    sub_date: "Jan 12, 2024",
    name: "Jane Smith",
    email: "jane.smith@gmail.com",
    number: "+1 000 000 0000",
    vin: "9090",
    plan: "DriveCar Plus",
    amount: "USD $100",
    duration: "Yearly",
    type: "Active",
  },
  {
    image: Profile4,
    sub_date: "Jan 12, 2024",
    name: "Jane Smith",
    email: "jane.smith@gmail.com",
    number: "+1 000 000 0000",
    vin: "9090",
    plan: "DriveCar Plus",
    amount: "USD $100",
    duration: "Yearly",
    type: "Active",
  },
  {
    image: Profile5,
    sub_date: "Jan 12, 2024",
    name: "Jane Smith",
    email: "jane.smith@gmail.com",
    number: "+1 000 000 0000",
    vin: "9090",
    plan: "DriveCar Plus",
    amount: "USD $100",
    duration: "Yearly",
    type: "Active",
  },
  {
    image: Profile6,
    sub_date: "Jan 12, 2024",
    name: "Jane Smith",
    email: "jane.smith@gmail.com",
    number: "+1 000 000 0000",
    vin: "9090",
    plan: "DriveCar Plus",
    amount: "USD $100",
    duration: "Yearly",
    type: "Active",
  },
  {
    image: Profile7,
    sub_date: "Jan 12, 2024",
    name: "Jane Smith",
    email: "jane.smith@gmail.com",
    number: "+1 000 000 0000",
    vin: "9090",
    plan: "DriveCar Plus",
    amount: "USD $100",
    duration: "Yearly",
    type: "Active",
  },
  {
    image: Profile8,
    sub_date: "Jan 12, 2024",
    name: "Jane Smith",
    email: "jane.smith@gmail.com",
    number: "+1 000 000 0000",
    vin: "9090",
    plan: "DriveCar Plus",
    amount: "USD $100",
    duration: "Yearly",
    type: "Active",
  },
  {
    image: Profile10,
    sub_date: "Jan 12, 2024",
    name: "Jane Smith",
    email: "jane.smith@gmail.com",
    number: "+1 000 000 0000",
    vin: "9090",
    plan: "DriveCar Plus",
    amount: "USD $100",
    duration: "Yearly",
    type: "Active",
  },
  {
    image: Profile10,
    sub_date: "Jan 12, 2024",
    name: "Jane Smith",
    email: "jane.smith@gmail.com",
    number: "+1 000 000 0000",
    vin: "9090",
    plan: "DriveCar Plus",
    amount: "USD $100",
    duration: "Yearly",
    type: "Active",
  },
];
